yolo_model:

  config_file:
    name: yolov3-farzan.cfg
  weight_file:
    name: yolov3-farzan.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Mug
      - Book
      - Mobile phone
      - Computer mouse
      - Pen
      - Computer monitor
